In [1]:
import numpy as np
import pandas as pd
import os
import time
import matplotlib.pyplot as plt
%matplotlib inline

import some_functions

In [2]:
f2 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/Lookups/Drug_LookUp.txt"
f3 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/Lookups/ChronicIllness_LookUp.txt"
f4 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/Lookups/patients.txt"
f5 = "C:/Users/ben/Desktop/MelbDatathon2017/fourthAttempt/remoteness2.csv"


Drug_LookUp = pd.read_table(filepath_or_buffer=f2, header=0)
ChronicIllness_LookUp = pd.read_table(filepath_or_buffer=f3, header=0)
Patients_LookUp = pd.read_table(filepath_or_buffer=f4, header=0)
remoteness = pd.read_table(filepath_or_buffer=f5, header=0, delimiter=',')

In [3]:
# i=26
# loc1 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/Transactions/patients_"
# f1 = loc1 + str(i) + '.txt'
# df = pd.read_table(filepath_or_buffer=f1, sep='\t', header=0)
# print(min(df.Patient_ID))

In [11]:
loc1 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/Transactions/patients_"
loc2 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/MISSING_TRANSACTIONS/missing_patients_"

aList = list()

start = time.time()

for i in range(1,26):
    
    
    f1 = loc1 + str(i) + '.txt'
    df = pd.read_table(filepath_or_buffer=f1, sep='\t', header=0)
    
    f2 = loc2 + str(i) + '.txt'
    df_missing = pd.read_table(filepath_or_buffer=f2, sep='\t', header=0)
    
    
    aList.append(some_functions.extract_features(df=df, df_missing=df_missing, ChronicIllness_LookUp=ChronicIllness_LookUp, Drug_LookUp=Drug_LookUp, Patients_LookUp=Patients_LookUp, remoteness=remoteness))

    elapsed = (time.time() - start)
    print("Time: " + str(round(elapsed, 4)) + " seconds, loop: " + str(i) )
    
    
    
result = pd.concat(aList)
result.shape

Time: 22.1034 seconds, loop: 1
Time: 43.3856 seconds, loop: 2
Time: 63.6006 seconds, loop: 3
Time: 84.4275 seconds, loop: 4
Time: 108.5878 seconds, loop: 5
Time: 136.1703 seconds, loop: 6
Time: 160.49 seconds, loop: 7
Time: 184.0637 seconds, loop: 8
Time: 207.8396 seconds, loop: 9
Time: 232.1719 seconds, loop: 10
Time: 254.5815 seconds, loop: 11
Time: 275.9938 seconds, loop: 12
Time: 297.6168 seconds, loop: 13
Time: 317.6309 seconds, loop: 14
Time: 337.1747 seconds, loop: 15
Time: 356.5523 seconds, loop: 16
Time: 375.8032 seconds, loop: 17
Time: 394.9356 seconds, loop: 18
Time: 414.5783 seconds, loop: 19
Time: 433.657 seconds, loop: 20
Time: 453.8637 seconds, loop: 21
Time: 473.9436 seconds, loop: 22
Time: 493.7289 seconds, loop: 23
Time: 513.0284 seconds, loop: 24
Time: 532.0899 seconds, loop: 25

(279200, 56)

In [12]:
result.head(7)

,Patient_ID,Diabetes_in_2016,Diabetes_length_time,Osteoporosis_length_time,Depression_length_time,Epilepsy_length_time,Lipids_length_time,Hypertension_length_time,Heart Failure_length_time,Anti-Coagulant_length_time,...,unknown_count,time_since_first,time_since_last,F,M,U,Inner Regional Australia,Major Cities of Australia,remote,ses_code
0,1.0,0,0.0,0.0,58.866667,43.7,0.000000,31.566667,0.000000,0.0,...,22.0,0.200000,60.866667,1,0,0,0.0,1.0,0.0,8.0
1,2.0,0,1.0,0.0,0.000000,0.0,54.200000,47.666667,0.000000,0.0,...,1.0,1.366667,60.633333,1,0,0,0.0,1.0,0.0,7.0
2,3.0,0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,37.0,3.466667,60.166667,0,1,0,1.0,0.0,0.0,8.0
3,4.0,0,0.0,0.0,0.000000,0.0,50.233333,0.000000,50.933333,0.0,...,5.0,1.833333,53.633333,0,0,1,0.0,1.0,0.0,6.0
4,5.0,0,0.0,0.0,0.000000,0.0,60.266667,0.000000,55.833333,0.0,...,62.0,0.433333,60.866667,0,0,1,0.0,1.0,0.0,9.0
5,6.0,0,0.0,0.0,46.733333,0.0,8.933333,0.000000,0.000000,0.0,...,43.0,1.133333,50.133333,0,0,1,0.0,1.0,0.0,10.0
6,7.0,1,1.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,38.466667,53.633333,0,1,0,0.0,1.0,0.0,10.0

In [13]:
result.columns

Index(['Patient_ID', 'Diabetes_in_2016', 'Diabetes_length_time',
       'Osteoporosis_length_time', 'Depression_length_time',
       'Epilepsy_length_time', 'Lipids_length_time',
       'Hypertension_length_time', 'Heart Failure_length_time',
       'Anti-Coagulant_length_time', 'Immunology_length_time',
       'Urology_length_time',
       'Chronic Obstructive Pulmonary Disease (COPD)_length_time',
       'Diabetes_time_since_2016', 'Osteoporosis_time_since_2016',
       'Depression_time_since_2016', 'Epilepsy_time_since_2016',
       'Lipids_time_since_2016', 'Hypertension_time_since_2016',
       'Heart Failure_time_since_2016', 'Anti-Coagulant_time_since_2016',
       'Immunology_time_since_2016', 'Urology_time_since_2016',
       'Chronic Obstructive Pulmonary Disease (COPD)_time_since_2016',
       'Diabetes_never_on', 'Osteoporosis_never_on', 'Depression_never_on',
       'Epilepsy_never_on', 'Lipids_never_on', 'Hypertension_never_on',
       'Heart Failure_never_on', 'Anti-Coagulant_never_on',
       'Immunology_never_on', 'Urology_never_on',
       'Chronic Obstructive Pulmonary Disease (COPD)_never_on',
       'PARACETAMOL_count', 'PERINDOPRIL_count', 'ESOMEPRAZOLE_count',
       'PANTOPRAZOLE_count', 'RAMIPRIL_count', 'AMLODIPINE_count',
       'OMEPRAZOLE_count', 'CLOPIDOGREL_count', 'LERCANIDIPINE_count',
       'RABEPRAZOLE_count', 'SALBUTAMOL CFC FREE_count', 'unknown_count',
       'time_since_first', 'time_since_last', 'F', 'M', 'U',
       'Inner Regional Australia', 'Major Cities of Australia', 'remote',
       'ses_code'],
      dtype='object')

In [14]:
name = "C:/Users/ben/Desktop/MelbDatathon2017/fourthAttempt/our_data.csv"
result.to_csv(path_or_buf=name, index = False)

In [8]:
# kaggle extraction
loc1 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/Transactions/patients_"
loc2 = "C:/Users/ben/Desktop/MelbDatathon2017/MelbDatathon2017/MISSING_TRANSACTIONS/missing_patients_"

aList = list()

start = time.time()

for i in range(26,51):
    
    
    f1 = loc1 + str(i) + '.txt'
    df = pd.read_table(filepath_or_buffer=f1, sep='\t', header=0)
    
    f2 = loc2 + str(i) + '.txt'
    df_missing = pd.read_table(filepath_or_buffer=f2, sep='\t', header=0)
    
    
    aList.append(some_functions.extract_features_from_kaggle(df=df, df_missing=df_missing, ChronicIllness_LookUp=ChronicIllness_LookUp, Drug_LookUp=Drug_LookUp, Patients_LookUp=Patients_LookUp, remoteness=remoteness))

    elapsed = (time.time() - start)
    print("Time: " + str(round(elapsed, 4)) + " seconds, loop: " + str(i) )
    
    
    
result_kdata = pd.concat(aList)
result_kdata.shape

Time: 20.9161 seconds, loop: 26
Time: 38.1597 seconds, loop: 27
Time: 54.5438 seconds, loop: 28
Time: 71.1011 seconds, loop: 29
Time: 88.6362 seconds, loop: 30
Time: 105.3709 seconds, loop: 31
Time: 122.0085 seconds, loop: 32
Time: 138.5678 seconds, loop: 33
Time: 154.9215 seconds, loop: 34
Time: 171.4487 seconds, loop: 35
Time: 188.1392 seconds, loop: 36
Time: 204.6952 seconds, loop: 37
Time: 221.2537 seconds, loop: 38
Time: 237.902 seconds, loop: 39
Time: 255.8108 seconds, loop: 40
Time: 274.2321 seconds, loop: 41
Time: 290.8424 seconds, loop: 42
Time: 307.3112 seconds, loop: 43
Time: 323.7897 seconds, loop: 44
Time: 340.2092 seconds, loop: 45
Time: 356.4239 seconds, loop: 46
Time: 373.0305 seconds, loop: 47
Time: 389.0136 seconds, loop: 48
Time: 405.1551 seconds, loop: 49
Time: 421.5246 seconds, loop: 50

(279152, 56)

In [9]:
#pd.set_option('display.max_columns', None)
result_kdata.head(7)

,Patient_ID,Diabetes_in_2016,Diabetes_length_time,Osteoporosis_length_time,Depression_length_time,Epilepsy_length_time,Lipids_length_time,Hypertension_length_time,Heart Failure_length_time,Anti-Coagulant_length_time,...,unknown_count,time_since_first,time_since_last,F,M,U,Inner Regional Australia,Major Cities of Australia,remote,ses_code
0,279201.0,0,0.000000,0.0,0.000000,0.000000,46.033333,49.066667,48.366667,0.000000,...,50.0,0.166667,48.466667,0,1,0,0.0,1.0,0.0,3.0
1,279202.0,0,0.000000,0.0,0.000000,0.000000,48.833333,0.000000,47.900000,10.566667,...,24.0,0.166667,48.000000,1,0,0,0.0,1.0,0.0,10.0
2,279203.0,0,0.000000,0.0,0.000000,0.000000,45.566667,0.000000,42.300000,0.000000,...,23.0,0.166667,48.233333,0,1,0,1.0,0.0,0.0,1.0
3,279204.0,0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,27.000000,48.466667,0,1,0,0.0,1.0,0.0,9.0
4,279205.0,0,0.000000,0.0,0.000000,2.866667,0.000000,0.000000,0.000000,0.000000,...,29.0,0.866667,47.766667,0,1,0,1.0,0.0,0.0,3.0
5,279206.0,0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.633333,48.233333,1,0,0,1.0,0.0,0.0,7.0
6,279207.0,1,43.466667,0.0,48.833333,0.000000,45.100000,0.000000,0.000000,0.000000,...,17.0,0.400000,48.233333,0,1,0,1.0,0.0,0.0,2.0

In [10]:
name = "C:/Users/ben/Desktop/MelbDatathon2017/fourthAttempt/our_data_from_kaggle_set.csv"
result_kdata.to_csv(path_or_buf=name, index = False)

In [15]:
min(result_kdata.Patient_ID)

279201.0